# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
cache: packages
branches:
  only:
  - master
r_check_args: --as-cran
